
import { StateMetadata } from './types';

export const STATE_METADATA: Record<string, StateMetadata> = {
  "Andhra Pradesh": { name: "Andhra Pradesh", clients: 120, status: 'Active' },
  "Arunachal Pradesh": { name: "Arunachal Pradesh", clients: 15, status: 'New' },
  "Assam": { name: "Assam", clients: 85, status: 'Growing' },
  "Bihar": { name: "Bihar", clients: 230, status: 'Active' },
  "Chhattisgarh": { name: "Chhattisgarh", clients: 95, status: 'Growing' },
  "NCT of Delhi": { name: "Delhi", clients: 850, status: 'Active' },
  "Delhi": { name: "Delhi", clients: 850, status: 'Active' },
  "Goa": { name: "Goa", clients: 45, status: 'Active' },
  "Gujarat": { name: "Gujarat", clients: 520, status: 'Active' },
  "Haryana": { name: "Haryana", clients: 310, status: 'Active' },
  "Himachal Pradesh": { name: "Himachal Pradesh", clients: 60, status: 'Growing' },
  "Jammu & Kashmir": { name: "Jammu & Kashmir", clients: 40, status: 'New' },
  "Jharkhand": { name: "Jharkhand", clients: 110, status: 'Growing' },
  "Karnataka": { name: "Karnataka", clients: 680, status: 'Active' },
  "Kerala": { name: "Kerala", clients: 210, status: 'Active' },
  "Ladakh": { name: "Ladakh", clients: 5, status: 'New' },
  "Madhya Pradesh": { name: "Madhya Pradesh", clients: 290, status: 'Active' },
  "Maharashtra": { name: "Maharashtra", clients: 950, status: 'Active' },
  "Manipur": { name: "Manipur", clients: 25, status: 'New' },
  "Meghalaya": { name: "Meghalaya", clients: 30, status: 'New' },
  "Mizoram": { name: "Mizoram", clients: 10, status: 'New' },
  "Nagaland": { name: "Nagaland", clients: 12, status: 'New' },
  "Odisha": { name: "Odisha", clients: 180, status: 'Growing' },
  "Punjab": { name: "Punjab", clients: 275, status: 'Active' },
  "Rajasthan": { name: "Rajasthan", clients: 410, status: 'Active' },
  "Sikkim": { name: "Sikkim", clients: 20, status: 'New' },
  "Tamil Nadu": { name: "Tamil Nadu", clients: 540, status: 'Active' },
  "Telangana": { name: "Telangana", clients: 460, status: 'Active' },
  "Tripura": { name: "Tripura", clients: 35, status: 'New' },
  "Uttar Pradesh": { name: "Uttar Pradesh", clients: 620, status: 'Active' },
  "Uttarakhand": { name: "Uttarakhand", clients: 130, status: 'Growing' },
  "West Bengal": { name: "West Bengal", clients: 390, status: 'Active' },
  "Andaman and Nicobar Islands": { name: "Andaman & Nicobar", clients: 8, status: 'New' },
  "Lakshadweep": { name: "Lakshadweep", clients: 2, status: 'New' },
  "Dadra and Nagar Haveli and Daman and Diu": { name: "Daman & Diu", clients: 15, status: 'New' },
  "Puducherry": { name: "Puducherry", clients: 25, status: 'Growing' }
};

export const SERVICES_LIST = [
  "Startup India Certificates",
  "Seed Funding Consultancy",
  "Tax Exemption",
  "ISO Certificate",
  "IEC Certificate",
  "MSME Certificate",
  "Grant Funds",
  "Business Loan",
  "Project Loan",
  "CGTMSE",
  "CGSS",
  "Mudra Loan",
  "Agricultural Loan",
  "FSSAI",
  "Digital Marketing",
  "Website Development",
  "Logo Design",
  "Trademark",
  "AI Solutions",
  "Whatsapp Blue Tick"
];
